<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a class="action reorder" href="<?php /* @escapeNotVerified */ echo $block->getReorderUrl($_order) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
        </a>
    <?php endif ?>
  <?php if ($this->helper('Alcatel\Poc\Helper\Data')->canCancel($_order->getEntityId())) : ?>
  <a class="action reorder" href="<?php echo $block->getUrl('poc/test/ordercancel', array('orderid' => $_order->getId())) ?>" class="link-cancel"><span>
  <?php echo 'Cancel'; ?></span></a> 
  <?php endif ?>
    <a class="action print"
       href="<?php /* @escapeNotVerified */ echo $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?php /* @escapeNotVerified */ echo __('Print Order') ?></span>
    </a>
    <?php echo $block->getChildHtml(); ?>
</div>
